In [ ]:
list_1 = [1.0, 1.0, 1.0, 1.0, 1.0]
list_1

[1.0, 1.0, 1.0, 1.0, 1.0]

In [ ]:
import numpy as np

ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [ ]:
type(ones_array)

numpy.ndarray

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
# matrix[Zeile, Spalte]

In [ ]:
matrix[0, 1]

2

In [ ]:
matrix[2, 0]

7

In [ ]:
# matrix[von:bis, von:bis]

In [ ]:
matrix[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matrix[:, 0]

array([1, 4, 7])